### PR TITLE
Figma implementation

### PR DESCRIPTION
**Pull request by birimbau**
Added some design as per FIGMA,

Font families and correct font sizes are still missing
Responsivness is still missing
Hydration is still missing

### CODE REVIEW

**Comment by parv3213** [comment]
Some observations-
- The input when in focus and not in hover, its background turns transparent. Also, should we remove the input outline? Screenshot 2023-07-07 at 4 29 40 PM
- We need to use a different font for `Data sent` (you have already mentioned this, but just keep this here so that we dont forgot). Screenshot 2023-07-07 at 4 33 04 PM
- If the background graphics are making the `data sent` text hard to read. The background to fix this.
- In the figma the links are underlined at all times. Screenshot 2023-07-07 at 4 35 05 PM
- Need to add a favicon

**Comment by parv3213** [comment]
@birimbau great work man. I am looking at your code and already learning a lot.

**Comment by birimbau** [comment]
@parv3213 
- Nice observation in the backgournd of inputs, its fixed now
- In the Data sent I added a blur so now its easier to read, aldo I changed the bg to a version with some opacity
- Hydration was fixed 👯 
- For the fonts and Links lets do that in another PR, so this is not blocked (Let me know if you disagree)
- For the Favicon, @Suede0619 can you provide one?

**Review by parv3213 — APPROVED** [review]

**Comment by parv3213** [comment]
> * In the figma the links are underlined at all times. Screenshot 2023-07-07 at 4 35 05 PM

Btw this one was missed.

**Pull request merged**
